default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  database: smartadmin_rails_full_development
  username: serenachang
  # password:
  host: localhost

test:
  adapter: postgresql
  database: smartadmin_rails_full_test
  username: serenachang
  # password:
  host: localhost

production:
  <<: *default
  database: smartadmin_rails_full
  username: smartadmin_rails_full
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
